version: '0.9.{build}'

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake Project\Tome.pro
  - mingw32-make

test_script:
  - qmake Project\TomeTest.pro "CONFIG+=debug"
  - mingw32-make
  - ..\Bin\debug\Tome\Tome.exe
